### ISSUE TITLE
master is crashing on mono after opening binary file

### ISSUE THREAD

**Issue by redvers** [davispuh/gear-emu#14] opened 2018-11-05 16:09 UTC
Greetings!

We're having a discussion about this on the //ax forums: http://forums.parallax.com/discussion/comment/1452183/#Comment_1452183

We have bisected the issue back and even checked across multiple versions of mono (4.4 -> 5.14).

Any assistance you could provide would be gratefully received.

**Comment by davispuh** [comment] 2018-11-05 19:32
Use some debbuger, set breakpoint on https://github.com/davispuh/gear-emu/blob/master/Gear/GUI/SpinView.cs#L176 then step till you'll find which line crashes.

**Comment by gatuno1** [comment] 2018-11-06 14:49
I think the problem is System.Window.Forms class itself. I remember that 4 years ago the framework was not ported to Linux by the mono Project. 
On Windows I was able to compile it with mono, but not in win*.

**Comment by jlunder** [comment] 2020-03-04 06:42
This is probably the bug I fixed in my PR https://github.com/davispuh/gear-emu/pull/17 -- if you still care, you can give that a try.

**Comment by drawkula** [comment] 2020-03-04 07:13
Status quo:
```
$ git log --max-count=3 --oneline 
15f5f20 (HEAD -> PR17) Prevent pathological copying of brushes, event storms on Linux
210fdb5 Fixed Z-flag behavior of instructions SUMC and SUMNC
74c355d (master) Bug correction on Logic View creation
```
Built on Debian10/AMD64:
```
$ ls -l Gear/bin/Release/Gear.exe
-rwxr-xr-x 1 yeti yeti 275968 Mar  4 06:54 Gear/bin/Release/Gear.exe
```
Indeed PR17 doesn't crash any more after loading a binary. But where is "Open Plugin" (as in V14.07.03) now? "Add Plugin" seems only to open the plugin's source in the editor... or is this a case of local PEBCAK?

**Comment by jlunder** [comment] 2020-03-04 07:38
Sorry, I'm completely new to this codebase, and realized a bit too late that the way I fixed things I probably broke the old plugin interface. (Like a fool I assumed the plugins were only the things in the project!)

However, that's not what you're saying, what you're saying is the UI is broken in a way you can't even TRY to load the plugin. I'm honestly not sure what this UI is supposed to look like, not having a Windows machine to compare against, but I don't think I changed that code. Maybe it's trying to load the plugin, failing, and opening an editor because it thinks you should fix the plugin?

If that's the case, you could try changing any "void Repaint(bool)" method to "void UpdateGui()" and see if you can load the plugin -- that's the interface change I made. I'm currently fixing some other random brokenness in the UI and trying to get it all to a point where I can load my project, which I'm trying to debug. When I'm done that, if people actually want this PR merged, I'll go over the plugin interface and add a compatibility layer so that plugins using the old interface can still load, as long as they're fairly independent of core.

Do people have a lot of custom one-off plugins? If it was up to me I'd prefer to hoist things into core code. Plugins are a pain in the ass, if the code is out there for all the plugins people actually use, it should just be in the core project and then anyone refactors core it'll be obvious that the plugin got broken and it can be fixed right away.

But I can understand why people might have custom plugins if they're emulating their own custom hardware or whatever, so I get the motivation.

**Comment by gatuno1** [comment] 2020-03-04 18:26
> Sorry, I'm completely new to this codebase, I literally picked it up on the weekend, and realized a bit too late that the way I fixed things I probably broke the old plugin interface. (Like a fool I assumed the plugins were only the things in the project! I didn't even realize there were XML plugins.)
Well, all the plugins are stored in xml format, and are editable by "open plugin" option.

> However, that's not what you're saying, what you're saying is the UI is broken in a way you can't even TRY to load the plugin. I'm honestly not sure what this UI is supposed to look like, not having a Windows machine to compare against, but I don't think I changed that code. Maybe it's trying to load the plugin, failing, and opening an editor because it thinks you should fix the plugin?

I would like to help you, compiling the pull requested version on windows. Please give me 2 days to do it.

> If that's the case, you could try changing any "void Repaint(bool)" method to "void UpdateGui()" and see if you can load the plugin -- that's the interface change I made. I'm currently fixing some other random brokenness in the UI and trying to get it all to a point where I can load my project, which I'm trying to debug. When I'm done that, if people actually want this PR merged, I'll go over the plugin interface and add a compatibility layer so that plugins using the old interface can still load, as long as they're fairly independent of core.
 
> Do people have a lot of custom one-off plugins? If it was up to me I'd prefer to hoist things into core code. Plugins are a pain in the ass, if the code is out there for all the plugins people actually use, it should just be in the core project and then anyone refactors core it'll be obvious that the plugin got broken and it can be fixed right away.
As long I know, I've seen only one plugin in proppeller forum, but I can't remember if it was in final stage so it couldn't be merged. 
I was trying to develop other myself, to get running the old OBEX example "[Eight Talking Cogs](http://obex.parallax.com/object/61)". The plugin editor worked OK, but I the plugin didn't work well. I discover there is a problem in the kernel of emulator (about the order when the plugins methods are evaluated if it make change on stimulus from one output pin to another input pin), but I didn't finish it. I would like to resume that investigation.
 
> But I can understand why people might have custom plugins if they're emulating their own custom hardware or whatever, so I get the motivation.
The original idea is to provide custom stimulus to the propeller.

**Comment by jlunder** [comment] 2020-03-06 10:32
@gatuno1 that's all good info. I may have restored the old plugin interface, I also did a little cleanup. I'm going to go through the views one by one and make sure they work. If you've got an ordering issue with your plugin, it's possible the plugin API needs to be modified to solve the problem...

**Comment by gatuno1** [comment] 2022-05-18 03:21
Today I've reproduce the error, using Ubuntu 22.04 on WSL2 on windows.
The interesting thing is the error message, not about drawing system or winforms, but about Microsoft.CSharp.CSharpCodeGenerator:
That's a start...
```
$ mono Gear.exe
System.SystemException: Error running mcs: Cannot find the specified file
  at Microsoft.CSharp.CSharpCodeGenerator.FromFileBatch (System.CodeDom.Compiler.CompilerParameters options, System.String[] fileNames) [0x0019a] in <a85c1a570f9a4f9f9c3d2cfa5504e34f>:0
  at Microsoft.CSharp.CSharpCodeGenerator.FromSourceBatch (System.CodeDom.Compiler.CompilerParameters options, System.String[] sources) [0x000ae] in <a85c1a570f9a4f9f9c3d2cfa5504e34f>:0
  at Microsoft.CSharp.CSharpCodeGenerator.System.CodeDom.Compiler.ICodeCompiler.CompileAssemblyFromSourceBatch (System.CodeDom.Compiler.CompilerParameters options, System.String[] sources) [0x00011] in <a85c1a570f9a4f9f9c3d2cfa5504e34f>:0
  at System.CodeDom.Compiler.CodeDomProvider.CompileAssemblyFromSource (System.CodeDom.Compiler.CompilerParameters options, System.String[] sources) [0x00006] in <a85c1a570f9a4f9f9c3d2cfa5504e34f>:0
  at Gear.PluginSupport.ModuleCompiler.LoadModule (System.String code, System.String className, System.String[] references, System.Object obj) [0x000d2] in <ce5a1a20b4a744c2aa58623529319e59>:0
  at Gear.GUI.Emulator.LoadPlugin (System.String FileName) [0x001f8] in <ce5a1a20b4a744c2aa58623529319e59>:0
  at Gear.GUI.Emulator.OpenPlugin_Click (System.Object sender, System.EventArgs e) [0x00053] in <ce5a1a20b4a744c2aa58623529319e59>:0
  at System.Windows.Forms.ToolStripItem.OnClick (System.EventArgs e) [0x0001c] in <a3daa9b84fd241a497578a25f68bc3c7>:0
  at System.Windows.Forms.ToolStripButton.OnClick (System.EventArgs e) [0x0001a] in <a3daa9b84fd241a497578a25f68bc3c7>:0
  at System.Windows.Forms.ToolStripItem.HandleClick (System.Int32 mouse_clicks, System.EventArgs e) [0x00036] in <a3daa9b84fd241a497578a25f68bc3c7>:0
  at System.Windows.Forms.ToolStripItem.FireEvent (System.EventArgs e, System.Windows.Forms.ToolStripItemEventType met) [0x00061] in <a3daa9b84fd241a497578a25f68bc3c7>:0
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.ToolStripItem.FireEvent(System.EventArgs,System.Windows.Forms.ToolStripItemEventType)
  at System.Windows.Forms.ToolStrip.OnMouseUp (System.Windows.Forms.MouseEventArgs mea) [0x00057] in <a3daa9b84fd241a497578a25f68bc3c7>:0
  at System.Windows.Forms.Control.WmLButtonUp (System.Windows.Forms.Message& m) [0x0007e] in <a3daa9b84fd241a497578a25f68bc3c7>:0
  at System.Windows.Forms.Control.WndProc (System.Windows.Forms.Message& m) [0x0016f] in <a3daa9b84fd241a497578a25f68bc3c7>:0
  at System.Windows.Forms.ScrollableControl.WndProc (System.Windows.Forms.Message& m) [0x00000] in <a3daa9b84fd241a497578a25f68bc3c7>:0
  at System.Windows.Forms.ToolStrip.WndProc (System.Windows.Forms.Message& m) [0x00000] in <a3daa9b84fd241a497578a25f68bc3c7>:0
  at System.Windows.Forms.Control+ControlWindowTarget.OnMessage (System.Windows.Forms.Message& m) [0x00000] in <a3daa9b84fd241a497578a25f68bc3c7>:0
  at System.Windows.Forms.Control+ControlNativeWindow.WndProc (System.Windows.Forms.Message& m) [0x0000b] in <a3daa9b84fd241a497578a25f68bc3c7>:0
  at System.Windows.Forms.NativeWindow.WndProc (System.IntPtr hWnd, System.Windows.Forms.Msg msg, System.IntPtr wParam, System.IntPtr lParam) [0x0008e] in <a3daa9b84fd241a497578a25f68bc3c7>:0
```

**Comment by gatuno1** [comment] 2022-05-18 16:22
Well, starting the investigation, I have a main suspect: missing components.
I started installing `mono-runtime`, and it crash. Added `libmono-system-windows-forms4.0-cil`, `libmono-csharp4.0c-cil` & `libmono-microsoft-csharp4.0-cil`, but crash it.
Finally tryed installing `mono-complete`, and it works!
![Captura](https://user-images.githubusercontent.com/8146845/169092562-293e9c23-2152-4a70-880f-5edb16bfc099.PNG)

The image show the latest Release 22.05.01, running vga plugin.

**Comment by gatuno1** [comment] 2022-05-18 16:26
As workaround for now, it works, but I need to figure what are the essencial packages...
The good news, it is no a compilation or compatibility problem, but enviroment instalation.

**Comment by drawkula** [comment] 2022-06-25 07:26
A déjà vu:  Version 22.6.2.0 crashes directly after loading a binary.

Debian11's mono-complete is installed.

Maybe [gear220602.log.txt.gz](https://github.com/davispuh/gear-emu/files/8984095/gear220602.log.txt.gz) helps a bit?

v220601 crashes too, but not v220504.

**Comment by gatuno1** [comment] 2022-06-26 20:27
> A déjà vu: Version 22.6.2.0 crashes directly after loading a binary.
> 
> Debian11's mono-complete is installed.
> 
> Maybe [gear220602.log.txt.gz](https://github.com/davispuh/gear-emu/files/8984095/gear220602.log.txt.gz) helps a bit?
> 
> v220601 crashes too, but not v220504.

With new Release v22.06.03 it is fixed!

**Closed** 2022-07-14 00:35 UTC
Labels: porting to linux
